### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by nikola-bozin-org**
remove all unensesary files and folders such a dist, tsconfig.ts, gitignore, etc...

 turned all scripts into js and updating the code so it all works.

### CODE REVIEW

**Comment by rexdavinci** [comment]
Does this support typescript projects?

**Comment by nikola-bozin-org** [comment]
> Does this support typescript projects?

Well, this is pure javascript code. I didn't made it typescript-compatible.

**Comment by rexdavinci** [comment]
I'll have to revert it. Could you test it against a typescript code and see if it works, then open the PR again. If it works with a typescript project, then it will work with javascript too. Thanks.

**Comment by nikola-bozin-org** [comment]
Probably, but not now... 
I also suggest if in a hurry, try to copy my javascript code, and just add the required types for arguments and interfaces for data.

**Comment by rishabhkeshan** [comment]
Hey @nikola-bozin-org @rexdavinci the current stable release doesnt support multiple compilations, any plans to release the fix?

**Comment by nikola-bozin-org** [comment]
> Hey @nikola-bozin-org @rexdavinci the current stable release doesnt support multiple compilations, any plans to release the fix?

Yes, here is stable version that supports multiple compilation: https://github.com/nikola-bozin-org/browser-solidity-compiler

**Comment by rishabhkeshan** [comment]
@nikola-bozin-org is it possible for you to create a NPM release for the same, I am working on a OSS project and importing the same as files won't be an option

**Comment by nikola-bozin-org** [comment]
it is possible. 
i will try to do it in less than 48 hours, if thats fine for you?

**Comment by rishabhkeshan** [comment]
I was actually looking to get something today as I have a deadline upcoming, it would be great if you could do it today, else if it's fine I can make a release of my own and publish it @nikola-bozin-org

**Comment by nikola-bozin-org** [comment]
Nope, unable to do it today.
If you intend to do the release, please inform me about.
I reliazed also that in my recent project i made some small changes to the compiler that i didnt push. There are just some minor simple changes we can talk about and i will inform you about them.
Directly contact me on: nikola.bozin.org@gmail.com

**Pull request merged**
